Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -38,44 +38,40 @@ jobs:
       - name: Blocklist Tests
         run: |
             echo "testing blocklist"
-            BLOCKLISTED_DOMAIN="doubleclick.net"
-            if curl -x http://localhost:3128 http://${BLOCKLISTED_DOMAIN} || true ; then
-               echo "Error: Blocklisted domain is reachable. Verify your blocklist settings."
-               exit 1
+            if curl -x http://localhost:3128 http://doubleclick.net || true; then
+              echo "Error: Blocklisted domain is reachable. Verify your blocklist settings."
+              exit 1
             else
-               echo "Ok: Blocklisted domain is not reachable."
+              echo "Ok: Blocklisted domain is not reachable."
             fi
-            BLOCKLISTED_IP="185.216.137.28"
-            if curl -x http://localhost:3128 http://${BLOCKLISTED_IP} || true ; then
+            if curl -x http://localhost:3128 http://185.216.137.28 || true; then
                echo "Error: Blocklisted ip is reachable. Verify your blocklist settings."
                exit 1
             else
-               echo "Ok: Blocklisted ip is not reachable."
+              echo "Ok: Blocklisted ip is not reachable."
             fi
 
       - name: Whitelist Tests
         run: |
           echo "testing whitelist"
-          WHITELISTED_DOMAIN="example.com"
-          if ! curl -x http://localhost:3128 http://${WHITELISTED_DOMAIN} || true ; then
-            echo "Error: Whitelisted domain is unreachable. Verify your whitelist settings."
-            exit 1
+          if ! curl -x http://localhost:3128 http://example.com || true; then
+             echo "Error: Whitelisted domain is unreachable. Verify your whitelist settings."
+              exit 1
           else
-            echo "Ok: Whitelisted domain is reachable."
+             echo "Ok: Whitelisted domain is reachable."
           fi
-          WHITELISTED_IP="192.168.1.1"
-          if ! curl -x http://localhost:3128 http://${WHITELISTED_IP} || true; then
-            echo "Error: Whitelisted IP is unreachable. Verify your whitelist settings."
-            exit 1
+          if ! curl -x http://localhost:3128 http://192.168.1.1 || true; then
+             echo "Error: Whitelisted IP is unreachable. Verify your whitelist settings."
+             exit 1
           else
             echo "Ok: Whitelisted IP is reachable."
           fi
 
+
       - name: Direct IP Connection Test
         run: |
             echo "testing direct connections"
-            DIRECT_IP="10.0.0.1"
-            if curl -x http://localhost:3128 http://${DIRECT_IP} --connect-timeout 10 || true ; then
+            if curl -x http://localhost:3128 http://10.0.0.1 --connect-timeout 10 || true ; then
                 echo "Error: Direct ip is reachable. Verify your network settings."
               exit 1
             else
@@ -85,53 +81,55 @@ jobs:
       - name: Authentication Test
         run: |
             echo "testing authentication"
-            AUTH_USER="testuser"
-            AUTH_PASS="testpassword"
-            if ! curl -x http://$AUTH_USER:$AUTH_PASS@localhost:3128 http://example.com --connect-timeout 10 || true ; then
+            if ! curl -x http://testuser:testpassword@localhost:3128 http://example.com --connect-timeout 10 || true ; then
                 echo "Error: Authentication failed. Verify your user settings."
               exit 1
             else
                 echo "Ok: Authentication successfull"
              fi
-            AUTH_PASS="invalid"
-           if  curl -x http://$AUTH_USER:$AUTH_PASS@localhost:3128 http://example.com --connect-timeout 10 || true; then
+            if  curl -x http://testuser:invalid@localhost:3128 http://example.com --connect-timeout 10 || true; then
                 echo "Error: Authentication should be failed with invalid password. Verify your user settings."
               exit 1
             else
                 echo "Ok: Authentication failed as expected"
              fi
+
       - name: Environment Variable Override Test
         run: |
-          echo "testing environment variables"
-          HTTP_PORT_CHECK=$(docker exec squid-proxy grep "http_port 3129" /etc/squid/squid.conf | wc -l)
-          if [ "$HTTP_PORT_CHECK" -ne "1" ]; then
-            echo "Error: http_port is not set with environment variables. Verify your env vars settings"
-            exit 1
-          else
-            echo "Ok: http_port set with environment variables"
-          fi
-
-          CACHE_DIR_CHECK=$(docker exec squid-proxy grep "cache_dir ufs /var/spool/squid 600" /etc/squid/squid.conf | wc -l)
-          if [ "$CACHE_DIR_CHECK" -ne "1" ]; then
-            echo "Error: cache_dir is not set with environment variables. Verify your env vars settings"
-             exit 1
-          else
-           echo "Ok: cache_dir set with environment variables"
-          fi
-          DNS_NAMESERVERS_CHECK=$(docker exec squid-proxy grep 'dns_nameservers' /etc/squid/squid.conf  | grep "8.8.8.8 8.8.4.4" | wc -l)
-          if [ "$DNS_NAMESERVERS_CHECK" -ne "0" ]; then
-             echo "Error: external dns is not set with environment variables. Verify your env vars settings"
-             exit 1
+           echo "testing environment variables"
+           
+           # Check http_port
+           if docker exec squid-proxy grep "http_port 3129" /etc/squid/squid.conf | grep -q .; then
+               echo "Ok: http_port set with environment variables"
            else
-            echo "Ok: external dns set correctly with environment variables"
-          fi
-          HTTPS_PORT_CHECK=$(docker exec squid-proxy grep "https_port 3130" /etc/squid/squid.conf | wc -l)
-          if [ "$HTTPS_PORT_CHECK" -ne "1" ]; then
-            echo "Error: https_port is not set with environment variables. Verify your env vars settings"
-              exit 1
-          else
+               echo "Error: http_port is not set with environment variables"
+               exit 1
+           fi
+
+           # Check cache_dir
+           if docker exec squid-proxy grep "cache_dir ufs /var/spool/squid 600" /etc/squid/squid.conf | grep -q .; then
+             echo "Ok: cache_dir set with environment variables"
+           else
+               echo "Error: cache_dir is not set with environment variables"
+               exit 1
+           fi
+
+
+           # Check external dns
+            if ! docker exec squid-proxy grep 'dns_nameservers' /etc/squid/squid.conf  | grep "8.8.8.8 8.8.4.4"  ; then
+                 echo "Ok: external dns set correctly with environment variables"
+             else
+                 echo "Error: external dns is not set correctly with environment variables"
+                 exit 1
+             fi
+
+           # Check https_port
+           if docker exec squid-proxy grep "https_port 3130" /etc/squid/squid.conf | grep -q .; then
              echo "Ok: https_port set correctly with environment variables"
-          fi
+           else
+             echo "Error: https_port is not set with environment variables"
+             exit 1
+           fi
       - name: Stop Docker container
         if: always()
         run: docker-compose down
